remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

title: Gretyl
description: Arcade, tools, and entries

navigation:
  - name: Arcade
    link: /#arcade
    sublist:
      - name: Artemis Trail
        link: /artemis-trail.html
      - name: Implode
        link: /implode.html
  - name: Tools
    link: /#tools
    sublist:
      - name: Shadertoy Harness
        link: /tools/shadertoy.html
      - name: webkitdirectory Demo
        link: /tools/webkitdirectory-demo/
  - name: Entries
    link: /#entries
    sublist:
      - name: Resnick Algorithms
        link: /resnick-algorithms/
      - name: Functional Data Structures
        link: /functional-data-structures/
